datasource:
    type: com.alibaba.druid.pool.DruidDataSource           #当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver           #mysql驱动包
    url: jdbc:mysql://localhost:3306/db2019?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root3
    password: 123456
